### ISSUE TITLE
Is it possible to search specific sections?

### ISSUE THREAD

**Issue by chrisyour** [wja-no/craft-weighted-search#1]
Hi there,

Love your weighted search plugin. Thanks so much for making it an releasing it into the wild. Is it possible to specify the specific sections of Craft that I want to search? (So I can control the types of entries returned.)

Thanks!

**Comment by oyvind-stenhaug** [comment]
Hi, thanks for your comment.

I think the functionality you describe would be a useful addition, but so far I haven't had time to implement it, I'm afraid.

**Comment by esseb** [comment]
@chrisyour I'll make a pull request when I have some spare time, but I hacked in support for this in my own project by editing `WeightedSearch_EntriesService.php`:

```
public function substringSearch($needle, $locale)
{
    // <new>
    $sectionIds = array(
        craft()->sections->getSectionByHandle('article')->id,
        craft()->sections->getSectionByHandle('blog')->id,
    );
    // </new>

    $result = array();
    $normalizedNeedle = StringHelper::normalizeKeywords($needle);
    $query = $this->getSearchIndexHits($normalizedNeedle, $locale);
    foreach ($query->queryAll() as $row) {
        $originalId = $row['elementId'];
        $entry = craft()->entries->getEntryById($originalId, $locale);

        $viewableEntry = $this->getViewableEntry($entry);
        if ($viewableEntry) {
            // <new>
            // Skip entries that are not within the sections we want.
            if (in_array($entry->sectionId, $sectionIds) === false) {
                continue;
            }
            // </new>

            $isViewableTitle = ($row['attribute'] === 'title' &&
                    $entry === $viewableEntry);
```

A few lines added, within the `<new>` comments. No lines edited.

Ideally sections to be included should be sent in when calling `craft.weightedSearch.substringSearch()` from the template.

**Comment by dovrosenberg** [comment]
This was super helpful, @esseb.  Thanks!  Great plugin, @oyvind-stenhaug.

**Comment by matt-adigital** [comment]
Hi, I've just had a look into this for our own uses and saw that this feature has not been implemented yet into the plugin. I've made some changes so that the plugin can now accept an array of sections to search through.

Here is an example of what we have done:
```
{% set sections = ["accommodation", "eventInfo", "events", "homepage", "howToBecomeASponsor", "news", "newsInfo", "participantInfo", "participantInformation", "pressMedia", "spectators", "sponsorsInfo", "termsOfDuty", "theCharity", "theCharityInfo"] %}
{% set results = craft.weightedSearch.substringSearch(query, sections) %}
```

The substringSearch tag still works without the additional parameter also. I have attached a zip file of my changes incase you guys want to add these changes into the plugin for a future release.

[weightedsearch.zip](https://github.com/wja-no/craft-weighted-search/files/636355/weightedsearch.zip)

We really enjoy using this plugin so thank you for creating it!

**Comment by oyvind-stenhaug** [comment]
Thanks, @matt-adigital! I'm in the process of including it and updating the documentation accordingly.

The only thing I don't quite see the reason for is the `sectionIds` if checks inside `if ($viewableEntry)`, since it seems to me that the sectionId filtering has already been taken care of by the extra WHERE clause in the SQL query.

I suppose it could check the section of `$viewableEntry` instead of `$entry` here, so maybe it was a typo, though it seems like a somewhat theoretical problem… (E.g. say there is a 'company' section whose entries don't have URLs, and a 'companyList' single which lists the companies and has some other content, and `getViewableEntry` has been customized to "forward" search hits in 'company' to the single; a search with sectionIds = `['company']` might then return the 'companyList' single if the if checks are not included. But that doesn't really seem so wrong to me.)

**Comment by matt-adigital** [comment]
Hi @oyvind-stenhaug,

The conditional you speak of was taken from the above code that @esseb posted. I then expanded on this by adding the separate query to speed up the process and prevent page load fails for larger sites. I've left the conditional in place though as a redundancy backup incase the entry model gives a null value or fails for some reason. I hope that clears up any confusion :)

**Comment by oyvind-stenhaug** [comment]
Thanks! I think I'll try omitting it when putting in the patch, since it was a bit confusing to me and seemed to work without. If the entry is null, $viewableEntry will be null as well, aside from the case of customized getViewableEntry, as described.

(I'm not very happy with the performance of the plugin, as you say it can result in page load fails for larger amounts of entries. The part that takes the most time is fetching each EntryModel, which seems non-trivial to get around, so definitely good to take the opportunity to reduce the amount if we're only interested in a subset of sections.)
