### ISSUE TITLE
v3 compatibility

### ISSUE THREAD

**Issue by mikestreety** [wja-no/craft-weighted-search#9]
Hey,

Love the plugin :) Any plans to upgrade to be compatible with Craft v3?

**Comment by oyvind-stenhaug** [comment]
Hi and thanks :)

We're using the plugin on some of our own projects, and are planning to upgrade those to Craft v3 to stay up-to-date. So yes, I haven't looked at Craft 3 in detail yet (since it's still in development), but as long as the features aren't supported natively, I expect we'll want to upgrade the plugin for v3 compatibility.

**Comment by mikestreety** [comment]
Great thanks! Will keep an eye out. From what I've seen (and understood) it's quite a big change (with regards to method names and such).
